server:
  port: ${PORT}
  servlet:
    encoding:
      charset: UTF-8

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 4
    driver-class-name: org.h2.Driver

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

aws:
  s3:
    bucket: ${S3_BUCKET_NAME}

security:
  jwt:
    token-key: ${JWT_TOKEN_KEY}
    secret-key: ${JWT_SECRET_KEY}