server:
  port: ${PORT}
  servlet:
    encoding:
      charset: UTF-8

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    url: jdbc:h2:mem://localhost/test
    username: sa
    password:
    hikari:
      maximum-pool-size: 4
    driver-class-name: org.h2.Driver